### ISSUE TITLE
Consolidate property processing and app initialization.

### ISSUE THREAD

**Issue by pfeairheller** [scoir/canis#59]
Using Viper, combine all the duplicated code across all the applications into one place, where possible.

Look at combining properties files where possible.  In other words, see if it makes sense for different components like issuer/verifier/loadbalancer to all use the same config file.

Goal is to get all items, **including Aries initialization** to be configurable from the properties files and not hardcoded.

**Comment by m00sey** [comment]
We can look at slicing extracting the common pieces (datastore-config) for example:

```
├── deploy
│   ├── compose
│   │   ├── canis-apiserver.yaml
│   │   ├── canis-datastore.yaml
│   │   ├── canis-didcomm-doorman.yaml
│   │   ├── canis-didcomm-issuer.yaml
│   │   ├── canis-didcomm-lb.yaml
│   │   ├── canis-ledgerstore.yaml
│   │   └── docker-compose.yml
```

And use the vipers merge config to load the pieces you need

```
viper.SetConfigName("apiserver")
viper.AddConfigPath(path)
viper.ReadInConfig()

if datastore != "" {
    viper.SetConfigName(datastore)
    viper.AddConfigPath(path)
    viper.MergeInConfig()
}
```

etc
