### ISSUE TITLE
Error on running make

### ISSUE THREAD

**Issue by domwoe** [scoir/canis#75]
**What I'm trying to do**

I'm trying to build/run canis
by running `make`

**Actual result**

```s
rm -f bin/*
go get "bou.ke/staticfiles@v0.0.0-20190225145250-827d7f6389cd"
go get "github.com/vektra/mockery/.../@v1.1.2"
go get "golang.org/x/tools/cmd/cover@v0.0.0-20200904140424-93eecc3576be"
go: found golang.org/x/tools/cmd/cover in golang.org/x/tools v0.0.0-20200904140424-93eecc3576be
go get "github.com/golang/protobuf/protoc-gen-go@v1.4.2"
go: found github.com/golang/protobuf/protoc-gen-go in github.com/golang/protobuf v1.4.2
make: staticfiles: No such file or directory
make: *** [pkg/static/canis-apiserver_swagger.go] Error 1
```

```s
go version go1.14.3 darwin/amd64
```
on a Mac Catalina

**Comment by m00sey** [comment]
If you run `go env` can you ensure `GOBIN` is on your path?

Thanks for the interest, for clarity this project is still very much in the development stage, so there will likely be many struggles getting up and running.

**Comment by domwoe** [comment]
Thanks for the heads up. `GOBIN` was set but not added to my `PATH`. 
It seems to be an rainy weekend anyways ;)
